# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(666, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 611, 411))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.user_label = QtWidgets.QLabel(self.widget)
        self.user_label.setObjectName("user_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.user_label)
        self.user = QtWidgets.QLabel(self.widget)
        self.user.setObjectName("user")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user)
        self.query_path_label = QtWidgets.QLabel(self.widget)
        self.query_path_label.setObjectName("query_path_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.query_path_label)
        self.query_button = QtWidgets.QPushButton(self.widget)
        self.query_button.setObjectName("query_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.query_button)
        self.query_path_browser = QtWidgets.QTextBrowser(self.widget)
        self.query_path_browser.setObjectName("query_path_browser")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.query_path_browser)
        self.max_bandwidth_label = QtWidgets.QLabel(self.widget)
        self.max_bandwidth_label.setObjectName("max_bandwidth_label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.max_bandwidth_label)
        self.choose_path_label = QtWidgets.QLabel(self.widget)
        self.choose_path_label.setObjectName("choose_path_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.choose_path_label)
        self.remaining_bandwidth_label = QtWidgets.QLabel(self.widget)
        self.remaining_bandwidth_label.setObjectName("remaining_bandwidth_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.remaining_bandwidth_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_6.addWidget(self.lcdNumber)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bandwidth_edit = QtWidgets.QLineEdit(self.widget)
        self.bandwidth_edit.setObjectName("bandwidth_edit")
        self.horizontalLayout_7.addWidget(self.bandwidth_edit)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.limit_button = QtWidgets.QPushButton(self.widget)
        self.limit_button.setObjectName("limit_button")
        self.horizontalLayout_7.addWidget(self.limit_button)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.formLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client GUI"))
        self.user_label.setText(_translate("MainWindow", "Current user:"))
        self.user.setText(_translate("MainWindow", "None"))
        self.query_path_label.setText(_translate("MainWindow", "Query Path"))
        self.query_button.setText(_translate("MainWindow", "Query !"))
        self.max_bandwidth_label.setText(_translate("MainWindow", "Max bandwidth"))
        self.choose_path_label.setText(_translate("MainWindow", "Choose Path"))
        self.remaining_bandwidth_label.setText(_translate("MainWindow", "Remaining bandwidth"))
        self.label_2.setText(_translate("MainWindow", "Mb/s"))
        self.pushButton.setText(_translate("MainWindow", "Query!"))
        self.label_4.setText(_translate("MainWindow", "Mb/s"))
        self.limit_button.setText(_translate("MainWindow", "Limit !"))


