# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 90, 711, 441))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 711, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_4.setStyleSheet("background: rgb(238, 255, 244)")
        self.widget_4.setObjectName("widget_4")
        self.charging_plan_label = QtWidgets.QLabel(self.widget_4)
        self.charging_plan_label.setGeometry(QtCore.QRect(10, 40, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.charging_plan_label.setFont(font)
        self.charging_plan_label.setObjectName("charging_plan_label")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 20, 581, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.user_path_vertical_layout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.user_path_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.user_path_vertical_layout.setObjectName("user_path_vertical_layout")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_5.setStyleSheet("background: rgb(238, 255, 244)")
        self.widget_5.setObjectName("widget_5")
        self.attention_label = QtWidgets.QLabel(self.widget_5)
        self.attention_label.setGeometry(QtCore.QRect(10, 30, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.attention_label.setFont(font)
        self.attention_label.setStyleSheet("")
        self.attention_label.setObjectName("attention_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 10, 521, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.attention_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.attention_label_2.setStyleSheet("")
        self.attention_label_2.setObjectName("attention_label_2")
        self.verticalLayout_3.addWidget(self.attention_label_2)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_2 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_2.setStyleSheet("background: rgb(255, 202, 192)")
        self.widget_2.setObjectName("widget_2")
        self.choose_charging_plan_label = QtWidgets.QLabel(self.widget_2)
        self.choose_charging_plan_label.setGeometry(QtCore.QRect(10, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.choose_charging_plan_label.setFont(font)
        self.choose_charging_plan_label.setObjectName("choose_charging_plan_label")
        self.charging_plan_comboBox = QtWidgets.QComboBox(self.widget_2)
        self.charging_plan_comboBox.setGeometry(QtCore.QRect(180, 40, 81, 31))
        self.charging_plan_comboBox.setObjectName("charging_plan_comboBox")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_3.setStyleSheet("background: rgb(255, 202, 192)")
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.widget_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 441, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.user_want_label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.user_want_label.setFont(font)
        self.user_want_label.setObjectName("user_want_label")
        self.horizontalLayout_6.addWidget(self.user_want_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_want_bandwidth_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.user_want_bandwidth_edit.setObjectName("user_want_bandwidth_edit")
        self.horizontalLayout.addWidget(self.user_want_bandwidth_edit)
        self.charging_plan_unit_label = QtWidgets.QLabel(self.layoutWidget2)
        self.charging_plan_unit_label.setObjectName("charging_plan_unit_label")
        self.horizontalLayout.addWidget(self.charging_plan_unit_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget2)
        self.total_lcdNumber.setObjectName("total_lcdNumber")
        self.horizontalLayout_2.addWidget(self.total_lcdNumber)
        self.charging_plan_total_label = QtWidgets.QLabel(self.layoutWidget2)
        self.charging_plan_total_label.setObjectName("charging_plan_total_label")
        self.horizontalLayout_2.addWidget(self.charging_plan_total_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.user_want_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.user_want_button.setObjectName("user_want_button")
        self.horizontalLayout_6.addWidget(self.user_want_button)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 30, 261, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_label = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.horizontalLayout_3.addWidget(self.user_label)
        self.user = QtWidgets.QLabel(self.layoutWidget3)
        self.user.setObjectName("user")
        self.horizontalLayout_3.addWidget(self.user)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 0, 321, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("scut.png"))
        self.label_2.setObjectName("label_2")
        self.layoutWidget.raise_()
        self.widget.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "用户可定义网络——用户客户端"))
        self.charging_plan_label.setText(_translate("MainWindow", "服务方案"))
        self.attention_label.setText(_translate("MainWindow", "注意事项          "))
        self.label.setText(_translate("MainWindow", "1. 输入带宽最大值不能超过剩余带宽"))
        self.attention_label_2.setText(_translate("MainWindow", "2. 可直接覆盖服务方案与输入带宽"))
        self.choose_charging_plan_label.setText(_translate("MainWindow", "选择服务方案"))
        self.user_want_label.setText(_translate("MainWindow", "请输入想要的带宽            "))
        self.charging_plan_unit_label.setText(_translate("MainWindow", "Mb"))
        self.charging_plan_total_label.setText(_translate("MainWindow", "$"))
        self.user_want_button.setText(_translate("MainWindow", "确认!"))
        self.user_label.setText(_translate("MainWindow", "当前用户"))
        self.user.setText(_translate("MainWindow", "None"))

