# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 60, 711, 441))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 711, 441))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget1)
        self.widget_4.setStyleSheet("background: rgb(238, 255, 244)")
        self.widget_4.setObjectName("widget_4")
        self.charging_plan_label = QtWidgets.QLabel(self.widget_4)
        self.charging_plan_label.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.charging_plan_label.setObjectName("charging_plan_label")
        self.layoutWidget = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 20, 581, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.user_path_vertical_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.user_path_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.user_path_vertical_layout.setObjectName("user_path_vertical_layout")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget1)
        self.widget_5.setStyleSheet("background: rgb(255, 233, 254)")
        self.widget_5.setObjectName("widget_5")
        self.attention_label = QtWidgets.QLabel(self.widget_5)
        self.attention_label.setGeometry(QtCore.QRect(10, 30, 81, 51))
        self.attention_label.setStyleSheet("")
        self.attention_label.setObjectName("attention_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 10, 521, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.attention_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.attention_label_2.setStyleSheet("")
        self.attention_label_2.setObjectName("attention_label_2")
        self.verticalLayout_3.addWidget(self.attention_label_2)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_2 = QtWidgets.QWidget(self.widget1)
        self.widget_2.setStyleSheet("background: rgb(255, 202, 192)")
        self.widget_2.setObjectName("widget_2")
        self.choose_charging_plan_label = QtWidgets.QLabel(self.widget_2)
        self.choose_charging_plan_label.setGeometry(QtCore.QRect(10, 30, 191, 41))
        self.choose_charging_plan_label.setObjectName("choose_charging_plan_label")
        self.charging_plan_comboBox = QtWidgets.QComboBox(self.widget_2)
        self.charging_plan_comboBox.setGeometry(QtCore.QRect(220, 40, 81, 31))
        self.charging_plan_comboBox.setObjectName("charging_plan_comboBox")
        self.choose_charging_plan_label.raise_()
        self.charging_plan_comboBox.raise_()
        self.attention_label.raise_()
        self.widget_5.raise_()
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget1)
        self.widget_3.setStyleSheet("background: rgb(255, 184, 195)")
        self.widget_3.setObjectName("widget_3")
        self.widget2 = QtWidgets.QWidget(self.widget_3)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 441, 81))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.user_want_label = QtWidgets.QLabel(self.widget2)
        self.user_want_label.setObjectName("user_want_label")
        self.horizontalLayout_6.addWidget(self.user_want_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_want_bandwidth_edit = QtWidgets.QLineEdit(self.widget2)
        self.user_want_bandwidth_edit.setObjectName("user_want_bandwidth_edit")
        self.horizontalLayout.addWidget(self.user_want_bandwidth_edit)
        self.charging_plan_unit_label = QtWidgets.QLabel(self.widget2)
        self.charging_plan_unit_label.setObjectName("charging_plan_unit_label")
        self.horizontalLayout.addWidget(self.charging_plan_unit_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_lcdNumber = QtWidgets.QLCDNumber(self.widget2)
        self.total_lcdNumber.setObjectName("total_lcdNumber")
        self.horizontalLayout_2.addWidget(self.total_lcdNumber)
        self.charging_plan_total_label = QtWidgets.QLabel(self.widget2)
        self.charging_plan_total_label.setObjectName("charging_plan_total_label")
        self.horizontalLayout_2.addWidget(self.charging_plan_total_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.user_want_button = QtWidgets.QPushButton(self.widget2)
        self.user_want_button.setObjectName("user_want_button")
        self.horizontalLayout_6.addWidget(self.user_want_button)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.attention_label.raise_()
        self.layoutWidget.raise_()
        self.attention_label.raise_()
        self.widget_2.raise_()
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(20, 20, 261, 21))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.user_label = QtWidgets.QLabel(self.widget3)
        self.user_label.setObjectName("user_label")
        self.horizontalLayout_3.addWidget(self.user_label)
        self.user = QtWidgets.QLabel(self.widget3)
        self.user.setObjectName("user")
        self.horizontalLayout_3.addWidget(self.user)
        self.widget.raise_()
        self.user_label.raise_()
        self.user.raise_()
        self.user_label.raise_()
        self.user.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client GUI"))
        self.charging_plan_label.setText(_translate("MainWindow", "Charging Plan"))
        self.attention_label.setText(_translate("MainWindow", "  Attention:    "))
        self.label.setText(_translate("MainWindow", " The bandwidth you want is limited by the free bandwidth above. "))
        self.attention_label_2.setText(_translate("MainWindow", "You can overwrite your charging plan as well as the desired bandwidth."))
        self.choose_charging_plan_label.setText(_translate("MainWindow", " Choose your charging plan:"))
        self.user_want_label.setText(_translate("MainWindow", " How much bandwidth do you want?"))
        self.charging_plan_unit_label.setText(_translate("MainWindow", "Mb"))
        self.charging_plan_total_label.setText(_translate("MainWindow", "$"))
        self.user_want_button.setText(_translate("MainWindow", "GO!"))
        self.user_label.setText(_translate("MainWindow", "Current user:"))
        self.user.setText(_translate("MainWindow", "None"))
